In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `cleaned_merged_cc_election.csv` data from the `Resources/Cleaned_CC_CSV/Final_CSV` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame

# Define the path to your CSV file
csv_file_path = Path('/Users/yegu/Documents/Project_4_Machine_learning_YG/Cleaned_CC_CSV/Sept27_CSV/Combined_Cleaned_CSV_cc_election/cleaned_merged_cc_election_with_2020_electionresult_no_vote_percentage.csv')

# Read the CSV file 
df_cc_election_votes_no_votepercent = pd.read_csv(csv_file_path)

# Now, the empty cells will not be represented as NaN in the DataFrame

# Review the DataFrame
df_cc_election_votes_no_votepercent.sort_values(by='STATE', ascending=True)

,STATE,YEAR,STNAME,TOT_MALE 15-49,TOT_MALE 50+,TOT_FEMALE 15-49,TOT_FEMALE 50+,WA_MALE 15-49,WA_MALE 50+,WA_FEMALE 15-49,...,NH_MALE 15-49,NH_MALE 50+,NH_FEMALE 15-49,NH_FEMALE 50+,H_MALE 15-49,H_MALE 50+,H_FEMALE 15-49,H_FEMALE 50+,party_won,Election_Winner
305,1,2000,alabama,948961,723520,970162,879279,678301,574154,660836,...,922424,717572,953358,873459,26537,5948,16804,5820,REPUBLICAN,0
65,1,2016,alabama,934280,961302,952796,1112359,628191,732190,616035,...,881691,940779,909701,1094521,52589,20523,43095,17838,REPUBLICAN,0
151,1,2012,alabama,942627,922382,959295,1067411,645318,708174,628679,...,887242,906195,917611,1053540,55385,16187,41684,13871,REPUBLICAN,0
164,1,2008,alabama,936594,847964,941712,1009669,651288,661054,629460,...,900249,835978,915923,998708,36345,11986,25789,10961,REPUBLICAN,0
204,1,2004,alabama,932204,779822,941659,936372,658174,612954,636800,...,901185,771440,920889,928553,31019,8382,20770,7819,REPUBLICAN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,56,2000,wyoming,109224,86286,104514,90787,103202,83748,98863,...,101172,82849,97264,87431,8052,3437,7250,3356,REPUBLICAN,0
90,56,2016,wyoming,120587,118333,109988,119797,110478,112840,101096,...,106253,110942,97471,112852,14334,7391,12517,6945,REPUBLICAN,0
108,56,2012,wyoming,120009,115418,108933,117463,110256,110380,100400,...,106340,108751,97324,111055,13669,6667,11609,6408,REPUBLICAN,0
220,56,2004,wyoming,106353,96093,100748,99889,99805,93035,94709,...,97545,92033,93084,95976,8808,4060,7664,3913,REPUBLICAN,0
0,56,2020,wyoming,118560,121387,107599,120335,108134,115622,98418,...,103761,113524,94888,112855,14799,7863,12711,7480,REPUBLICAN,0

In [4]:
#drop the STNAME and party_won column
df_lr_no_vote_percent=df_cc_election_votes_no_votepercent.drop(columns=['STNAME','party_won'])
df_lr_no_vote_percent

,STATE,YEAR,TOT_MALE 15-49,TOT_MALE 50+,TOT_FEMALE 15-49,TOT_FEMALE 50+,WA_MALE 15-49,WA_MALE 50+,WA_FEMALE 15-49,WA_FEMALE 50+,...,TOM_FEMALE 50+,NH_MALE 15-49,NH_MALE 50+,NH_FEMALE 15-49,NH_FEMALE 50+,H_MALE 15-49,H_MALE 50+,H_FEMALE 15-49,H_FEMALE 50+,Election_Winner
0,56,2020,118560,121387,107599,120335,108134,115622,98418,114586,...,1317,103761,113524,94888,112855,14799,7863,12711,7480,0
1,47,2020,1367375,1393501,1353192,1550693,1046105,1170795,1017474,1274952,...,13672,1265101,1349658,1263543,1511493,102274,43843,89649,39200,0
2,36,2020,4033040,4042015,3995264,4584642,2718640,3003871,2615963,3299508,...,65229,3126589,3444493,3134479,3892210,906451,597522,860785,692432,1
3,37,2020,2070745,2095415,2042064,2362670,1418891,1613063,1359952,1761349,...,23337,1814246,1977820,1807250,2253915,256499,117595,234814,108755,0
4,16,2020,378695,361364,364030,372891,347908,344297,334137,354741,...,5029,318145,333793,308479,346988,60550,27571,55551,25903,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,29,2000,1204434,917911,1206511,1096942,1027607,829408,1013743,979160,...,7636,1170020,908075,1178254,1086597,34414,9836,28257,10345,0
302,50,2000,129539,107563,130514,121934,125208,105698,126215,119934,...,813,128130,106999,129121,121294,1409,564,1393,640,1
303,12,2000,3298352,2974444,3232749,3500864,2614251,2641710,2505295,3088366,...,20218,2605187,2613982,2600694,3063195,693165,360462,632055,437669,1
304,16,2000,290323,205306,278632,221525,276712,199851,265538,215354,...,1557,261035,198208,255309,215289,29288,7098,23323,6236,0
305,1,2000,948961,723520,970162,879279,678301,574154,660836,677168,...,5314,922424,717572,953358,873459,26537,5948,16804,5820,0

### Step 2: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [5]:
# Check the balance of our target values
df_lr_no_vote_percent["Election_Winner"].value_counts()

0    161
1    145
Name: Election_Winner, dtype: int64

### Step 3: Split the data into training and testing datasets by using `train_test_split`. Train on 2000-2016 and Test on 2020

In [7]:
# Filter data for the training set (2000-2016) and the testing set (2020)
training_data = df_lr_no_vote_percent[df_lr_no_vote_percent['YEAR'].between(2000, 2016)]
testing_data = df_lr_no_vote_percent[df_lr_no_vote_percent['YEAR'] == 2020]

# Separate the dependent variable (Y) and independent variables (X) for both sets
X_train = training_data.drop(columns=['Election_Winner', 'YEAR'])  
y_train = training_data['Election_Winner']

X_test = testing_data.drop(columns=['Election_Winner', "YEAR"])    
y_test = testing_data['Election_Winner']

# Split the data into training and testing sets (you can adjust the test_size as needed)
#X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Now you have X_train, y_train for training (2000-2016), and X_test, y_test for testing (2020)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the Logistic Regression model
lr_model = LogisticRegression(solver='liblinear', random_state=42)

# Fit the model using training data
lr_model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42, solver='liblinear')

###  Step 2: Save the predictions on the testing data labels by using the testing feature data (X_test) and the fitted model.

In [9]:
# Make predictions on the test set
testing_predictions = lr_model.predict(X_test_scaled)
testing_predictions_df = pd.DataFrame({"Prediction": testing_predictions, "Actual": y_test})
#pd.DataFrame({"Prediction": testing_predictions, "Actual": y_test})
testing_predictions_df

    Prediction  Actual
0            0       0
1            0       0
2            1       1
3            0       0
4            0       0
5            0       0
6            1       1
7            1       0
8            0       0
9            1       1
10           0       0
11           1       1
12           0       1
13           0       1
14           0       1
15           0       0
16           0       0
17           1       1
18           0       1
19           1       0
20           0       0
21           1       1
22           1       1
23           1       1
24           1       1
25           0       0
26           0       0
27           0       0
28           1       1
29           1       0
30           0       0
31           1       0
32           1       1
33           1       1
34           1       0
35           1       1
36           0       1
37           1       1
38           1       1
39           0       0
40           1       1
41           0       0
42           0       0
43           1       1
44           0       1
45           0       0
46           0       1
47           0       0
48           1       1
49           1       1
50           1       0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [10]:
# Print the balanced_accuracy score of the model
print( f'The balanced accuracy score of the model is : {balanced_accuracy_score(y_test, testing_predictions)}')

The balanced accuracy score of the model is : 0.7453846153846153

In [11]:
# Generate a confusion matrix for the model
confusion_matrix(y_test, testing_predictions)

array([[19,  6],
       [ 7, 19]])

In [12]:
# Print the classification report for the model

print(classification_report(y_test, testing_predictions))

              precision    recall  f1-score   support

           0       0.73      0.76      0.75        25
           1       0.76      0.73      0.75        26

    accuracy                           0.75        51
   macro avg       0.75      0.75      0.75        51
weighted avg       0.75      0.75      0.75        51

### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (Republican) and `1` (Democrat) winner in each state? winner_mapping = {'DEMOCRAT': 1, 'REPUBLICAN': 0}

**Answer:** The logistic regression model is be doing very well in predicting the both the `0` (Republican) and `1` (Democrat) winner in each state with precision, recall, and f1-score of 0.88.

In [25]:
# Define a mapping dictionary 
#winner_mapping = {'DEMOCRAT': 1, 'REPUBLICAN': 0}

# Determine Which States are Swing States

In [13]:
# Predict probabilities for the test set
y_probabilities = pd.DataFrame(lr_model.predict_proba(X_test_scaled))

In [14]:
y_probabilities_df=y_probabilities.rename(columns={0:"Republic_Prob",1:"Democrat_Prob"})

In [15]:
y_probabilities_df

    Republic_Prob  Democrat_Prob
0        0.655392       0.344608
1        0.705377       0.294623
2        0.000102       0.999898
3        0.865530       0.134470
4        0.552998       0.447002
5        0.641311       0.358689
6        0.009148       0.990852
7        0.306381       0.693619
8        0.962952       0.037048
9        0.350827       0.649173
10       0.531858       0.468142
11       0.066572       0.933428
12       0.604300       0.395700
13       0.567363       0.432637
14       0.517567       0.482433
15       0.839672       0.160328
16       0.699579       0.300421
17       0.034824       0.965176
18       0.895496       0.104504
19       0.356068       0.643932
20       0.861483       0.138517
21       0.289522       0.710478
22       0.442369       0.557631
23       0.157605       0.842395
24       0.483455       0.516545
25       0.839441       0.160559
26       0.517707       0.482293
27       0.662381       0.337619
28       0.004048       0.995952
29       0.475808       0.524192
30       0.536642       0.463358
31       0.476351       0.523649
32       0.262854       0.737146
33       0.461465       0.538535
34       0.381540       0.618460
35       0.296441       0.703559
36       0.826463       0.173537
37       0.121231       0.878769
38       0.000000       1.000000
39       0.802942       0.197058
40       0.376434       0.623566
41       0.578106       0.421894
42       0.677371       0.322629
43       0.014987       0.985013
44       0.815749       0.184251
45       0.653878       0.346122
46       0.585096       0.414904
47       0.699697       0.300303
48       0.026286       0.973714
49       0.449005       0.550995
50       0.320905       0.679095

In [16]:
# Reset the indices of the test set
y_probabilities_df.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)

#y_probabilities_df['Index'] = X_test.index  # Add the index column from X_test

# Assuming you have a reference to the original test data in 'original_test_data'
# and it includes a 'STATE' column
df_probability_vote_with_state = pd.concat([y_probabilities_df, X_test['STATE']], axis=1)

# Reset the DataFrame index
df_probability_vote_with_state.reset_index(drop=True, inplace=True)


# Print the DataFrame with STATE column
print("Predicted Probabilities for each class (in percentages) with STATE column:")
df_probability_vote_with_state

Predicted Probabilities for each class (in percentages) with STATE column:

    Republic_Prob  Democrat_Prob  STATE
0        0.655392       0.344608     56
1        0.705377       0.294623     47
2        0.000102       0.999898     36
3        0.865530       0.134470     37
4        0.552998       0.447002     16
5        0.641311       0.358689     38
6        0.009148       0.990852     15
7        0.306381       0.693619     39
8        0.962952       0.037048     40
9        0.350827       0.649173     41
10       0.531858       0.468142     12
11       0.066572       0.933428     42
12       0.604300       0.395700     11
13       0.567363       0.432637     44
14       0.517567       0.482433     10
15       0.839672       0.160328     45
16       0.699579       0.300421     46
17       0.034824       0.965176     17
18       0.895496       0.104504     35
19       0.356068       0.643932     18
20       0.861483       0.138517     22
21       0.289522       0.710478     26
22       0.442369       0.557631     24
23       0.157605       0.842395     27
24       0.483455       0.516545     23
25       0.839441       0.160559     28
26       0.517707       0.482293     29
27       0.662381       0.337619     30
28       0.004048       0.995952     34
29       0.475808       0.524192     21
30       0.536642       0.463358     31
31       0.476351       0.523649     20
32       0.262854       0.737146     32
33       0.461465       0.538535     33
34       0.381540       0.618460     19
35       0.296441       0.703559      9
36       0.826463       0.173537     13
37       0.121231       0.878769     51
38       0.000000       1.000000      6
39       0.802942       0.197058      1
40       0.376434       0.623566     55
41       0.578106       0.421894     54
42       0.677371       0.322629      2
43       0.014987       0.985013     53
44       0.815749       0.184251      4
45       0.653878       0.346122      5
46       0.585096       0.414904     50
47       0.699697       0.300303     49
48       0.026286       0.973714     25
49       0.449005       0.550995      8
50       0.320905       0.679095     48

In [17]:
df_2020_State= df_cc_election_votes_no_votepercent[df_cc_election_votes_no_votepercent['YEAR'] == 2020][['STATE', 'STNAME']]
df_2020_State

    STATE                STNAME
0      56               wyoming
1      47             tennessee
2      36              new york
3      37        north carolina
4      16                 idaho
5      38          north dakota
6      15                hawaii
7      39                  ohio
8      40              oklahoma
9      41                oregon
10     12               florida
11     42          pennsylvania
12     11  district of columbia
13     44          rhode island
14     10              delaware
15     45        south carolina
16     46          south dakota
17     17              illinois
18     35            new mexico
19     18               indiana
20     22             louisiana
21     26              michigan
22     24              maryland
23     27             minnesota
24     23                 maine
25     28           mississippi
26     29              missouri
27     30               montana
28     34            new jersey
29     21              kentucky
30     31              nebraska
31     20                kansas
32     32                nevada
33     33         new hampshire
34     19                  iowa
35      9           connecticut
36     13               georgia
37     51              virginia
38      6            california
39      1               alabama
40     55             wisconsin
41     54         west virginia
42      2                alaska
43     53            washington
44      4               arizona
45      5              arkansas
46     50               vermont
47     49                  utah
48     25         massachusetts
49      8              colorado
50     48                 texas

In [18]:
merged_df_predit_election_vote_state_prob = pd.merge(df_probability_vote_with_state, df_2020_State, on='STATE', how='inner')
merged_df_predit_election_vote_state_prob

    Republic_Prob  Democrat_Prob  STATE                STNAME
0        0.655392       0.344608     56               wyoming
1        0.705377       0.294623     47             tennessee
2        0.000102       0.999898     36              new york
3        0.865530       0.134470     37        north carolina
4        0.552998       0.447002     16                 idaho
5        0.641311       0.358689     38          north dakota
6        0.009148       0.990852     15                hawaii
7        0.306381       0.693619     39                  ohio
8        0.962952       0.037048     40              oklahoma
9        0.350827       0.649173     41                oregon
10       0.531858       0.468142     12               florida
11       0.066572       0.933428     42          pennsylvania
12       0.604300       0.395700     11  district of columbia
13       0.567363       0.432637     44          rhode island
14       0.517567       0.482433     10              delaware
15       0.839672       0.160328     45        south carolina
16       0.699579       0.300421     46          south dakota
17       0.034824       0.965176     17              illinois
18       0.895496       0.104504     35            new mexico
19       0.356068       0.643932     18               indiana
20       0.861483       0.138517     22             louisiana
21       0.289522       0.710478     26              michigan
22       0.442369       0.557631     24              maryland
23       0.157605       0.842395     27             minnesota
24       0.483455       0.516545     23                 maine
25       0.839441       0.160559     28           mississippi
26       0.517707       0.482293     29              missouri
27       0.662381       0.337619     30               montana
28       0.004048       0.995952     34            new jersey
29       0.475808       0.524192     21              kentucky
30       0.536642       0.463358     31              nebraska
31       0.476351       0.523649     20                kansas
32       0.262854       0.737146     32                nevada
33       0.461465       0.538535     33         new hampshire
34       0.381540       0.618460     19                  iowa
35       0.296441       0.703559      9           connecticut
36       0.826463       0.173537     13               georgia
37       0.121231       0.878769     51              virginia
38       0.000000       1.000000      6            california
39       0.802942       0.197058      1               alabama
40       0.376434       0.623566     55             wisconsin
41       0.578106       0.421894     54         west virginia
42       0.677371       0.322629      2                alaska
43       0.014987       0.985013     53            washington
44       0.815749       0.184251      4               arizona
45       0.653878       0.346122      5              arkansas
46       0.585096       0.414904     50               vermont
47       0.699697       0.300303     49                  utah
48       0.026286       0.973714     25         massachusetts
49       0.449005       0.550995      8              colorado
50       0.320905       0.679095     48                 texas

In [19]:
merged_df_predit_election_vote_state_prob.sort_values(by='STNAME', ascending=True, inplace=True)

In [20]:
merged_df_predit_election_vote_state_prob.head()

    Republic_Prob  Democrat_Prob  STATE      STNAME
39       0.802942       0.197058      1     alabama
42       0.677371       0.322629      2      alaska
44       0.815749       0.184251      4     arizona
45       0.653878       0.346122      5    arkansas
38       0.000000       1.000000      6  california

In [36]:
#save the dataframe to excel

# Specify the folder path and Excel file name
folder_path = '/Users/yegu/Documents/Project_4_Machine_learning_YG/Sept27/Prediction_Result/Election_Result_Prediction.xlsx'


# Use the to_excel method to save the DataFrame to the Excel file
merged_df_predit_election_vote_state_prob.to_excel(folder_path, index=False)  

print(f"election prediction probabilty saved to {folder_path}")

election prediction probabilty saved to /Users/yegu/Documents/Project_4_Machine_learning_YG/Sept27/Prediction_Result/Election_Result_Prediction.xlsx

---